# Backstage override configuration for your local development environment
backend:
  database:
    client: better-sqlite3
    connection: ':memory:'
    # config options: https://node-postgres.com/apis/client
    # client: pg
    # connection:
    #   host: ${POSTGRES_HOST}
    #   port: ${POSTGRES_PORT}
    #   user: ${POSTGRES_USER}
    #   password: ${POSTGRES_PASSWORD}

auth:
  environment: development
  providers:
    guest: {}
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        ## uncomment if using GitHub Enterprise
        # enterpriseInstanceUrl: ${AUTH_GITHUB_ENTERPRISE_INSTANCE_URL}
        # signIn:
        #   resolvers:
        #   # See https://backstage.io/docs/auth/github/provider#resolvers for more resolvers
        #   - resolver: usernameMatchingUserEntityName

integrations:
  github:
  - host: github.com
    token: ${GITHUB_TOKEN}
  #  callbackUrl: ${BASEURL_LOCAL_CALLBACK}
  # - host: ghe.example.net
  #   apiBaseUrl: https://ghe.example.net/api/v3
  #   rawBaseUrl: https://ghe.example.net/raw
  #   token: ${GHE_TOKEN}



