apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  tags:
  - node
  - javascript
  - scaffolder
  # Example for optional annotations
  annotations:
    # terraform/organization: orgName
    # terraform/workspaces: workspaceName1,workspaceName2,workspaceName3
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: user:guest
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-advanced-template
  description: Template avançado para projetos Python.
  tags:
  - python
  - scaffolder
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
spec:
  type: template
  owner: user:carlos
  path: ./templates/python-advanced-template/template.yaml
  lifecycle: experimental
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
    # terraform/organization: orgName
    # terraform/workspaces: workspaceName1,workspaceName2,workspaceName3
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  annotations:
    # sonarqube.org/project-key: ${SONARQUBE_YOUR_INSTANCE_NAME}/${SONARQUBE_YOUR_PROJECT_KEY}
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  owner: CNCF
  lifecycle: experimental
