apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental

# ---
# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: backstage
#   description: |
#     Backstage is an open-source developer portal that puts the developer experience first.
#   annotations:
#     sonarqube.org/project-key: ${SONARQUBE_TOKEN} #YOUR_INSTANCE_NAME/YOUR_PROJECT_KEY
# spec:
#   type: library
#   owner: CNCF
#   lifecycle: experimental
