apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  tags:
  - node
  - scaffolder
  # Example for optional annotations
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-advanced-template
  description: Template avançado para projetos Python.
  tags:
  - python
  - scaffolder
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
spec:
  type: template
  owner: user:carlos
  path: ./templates/python-advanced-template/template.yaml
  lifecycle: experimental
