---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: devops
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-advanced-template
  description: Template avançado para projetos Python.
  tags:
  - python
  - scaffolder
spec:
  type: template
  owner: user:carlos
  path: ./templates/python-advanced-template/template.yaml
  lifecycle: experimental
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-grpc-api
spec:
  type: grpc
  lifecycle: experimental
  owner: guest/guests
  system: examples
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system
spec:
  owner: devops
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
  tags:
    - Nodejs
spec:
  type: template
  lifecycle: experimental
  owner: user:carlos
  system: python
  providesApis: []
---


