---
# USERS
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: guest
    email: gues@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [ team-a, team-b, employees ]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jdoe
spec:
  profile:
    displayName: Jenny Doe
    email: jenny-doe@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [ team-a, team-b, employees ]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: carlos
spec:
  profile:
    displayName: Carlos Roberto dos Santos Silva
    email: carlos.roberto.devps@gmail.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [ guest, employees, devops, maintainers, idpadmins, default, team-a, team-b ]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: maintainers
spec:
  profile:
    displayName: The Maintainers Unit
    email: maintainerse@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [ team-b, employees. devops, idpadmins, defaulf, team-a, team-b ]
---

# GROUPS
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: employees
  description: The Employees Unit
spec:
  type: team
  profile:
    displayName: Employees
    email: carlos.roberto.devps@gmail.com.com
    picture: https://example.com/groups/team.jpeg
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: devops
  description: The Devops Unit
spec:
  type: team
  profile:
    displayName: DevOps, FullCycle and FullStack
    email: carlos.roberto.devps@gmail.com.com
    picture: https://example.com/groups/team.jpeg
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: idpadmins
  description: The infra business unit
spec:
  type: business-unit
  profile:
    displayName: The Infrastructure Unit
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-a
  description: team-a
spec:
  type: team
  profile:
    displayName: team-a
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-b
  description: team-b
spec:
  type: team
  profile:
    displayName: team-b
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: default
  description: Default Developments
spec:
  type: business-unit
  profile:
    displayName: default
    email: guest@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: maintainers
  description: Default Maintainers
spec:
  type: business-unit
  profile:
    displayName: Maintainers
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: artist-relations-team
  description: artist-relations-team
spec:
  type: team
  profile:
    displayName: artist-relations-team
    email: artist-relations-team@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: []
