---
# USERS
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: guest
    email: gues@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [ guests, team-a, team-b, employees ]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jdoe
spec:
  profile:
    displayName: Jenny Doe
    email: jenny-doe@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [ guests, team-a, team-b, employees ]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: sda-se-reviewer
spec:
  profile:
    displayName: sda-se-reviewer
    email: sda-se-reviewers@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [ guests, team-a, team-b, employees ]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: carlos
spec:
  profile:
    displayName: Carlos Roberto dos Santos Silva
    email: carlos.roberto.devps@gmail.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [ guests, employees, devops, maintainers, idpadmins, default, team-a, team-b ]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: maintainers
spec:
  profile:
    displayName: The Maintainers Unit
    email: maintainerse@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [ guests, team-b, employees. devops, idpadmins, defaulf, team-a, team-b ]
---

# GROUPS
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: employees
  description: The Employees Unit
spec:
  type: team
  profile:
    displayName: The Employees Unit
    email: employeess@gmail.com.com
    picture: https://example.com/groups/team.jpeg
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: devops
  description: The Devops Unit
spec:
  type: team
  profile:
    displayName: DevOps, FullCycle and FullStack
    email: devops@gmail.com.com
    picture: https://example.com/groups/team.jpeg
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: idpadmins
  description: The infra business unit
spec:
  type: team
  profile:
    displayName: The Infrastructure Unit
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-a
  description: team-a
spec:
  type: team
  profile:
    displayName: team-a
    email: team-a@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-b
  description: team-b
spec:
  type: team
  profile:
    displayName: team-b
    email: team-b@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: default
  description: Default Developments
spec:
  type: team
  profile:
    displayName: Default
    email: default@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: maintainers
  description: Default Maintainers Unit
spec:
  type: team
  profile:
    displayName: The Maintainers Unit
    email: maintainers@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: artist-relations-team
  description: artist-relations-team
spec:
  type: team
  profile:
    displayName: The artist-relations-team Unit
    email: artist-relations-team@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sda-se-reviewers
  description: sda-se-reviewers
spec:
  type: team
  profile:
    displayName: The sda-se-reviewers Unit
    email: sda-se-reviewers@example.com
    picture: https://example.com/groups/sda-se-reviewers.jpeg
  children: []
