apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-advanced-template
  description: Template avançado para projetos Python.
  tags:
  - python
  - scaffolder
spec:
  type: template
  owner: user:carlos
  # path: ./templates/python-advanced-template/template.yaml
  lifecycle: experimental